parameters:

services:
    birrols_user.registration.form.type:
        class: Birrols\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: birrols_user_registration }

    birrols_user.profile.form.type:
        class: Birrols\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: birrols_user_profile }

# https://gist.github.com/1670163
    birrols_user.security.interactive_login_listener:
        class: Birrols\UserBundle\EventListener\UserListener
        calls:
            - [ setSession, ['@session'] ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: setLocaleForAuthenticatedUser }

    birrols_user.security.kernel_request_listener:
        class: Birrols\UserBundle\EventListener\UserListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setLocaleForUnauthenticatedUser }