hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /oauth/redirect
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /oauth/connect
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /oauth/login
google_login:
    pattern: /loginOA/check-google    
facebook_login:
    pattern: /loginOA/check-facebook
foursquare_login:
    pattern: /loginOA/check-foursquare    
twitter_login:
    pattern: /loginOA/check-twitter    

