parameters:
#    birrols_beer.example.class: Birrols\BeerBundle\Example

services:
#    birrols_beer.example:
#        class: %birrols_beer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
