Countries:
    type: entity
    table: countries
    fields:
        autoId:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: auto_id
            generator:
                strategy: IDENTITY
        languageId:
            type: boolean
            nullable: false
            column: language_id
        name:
            type: string
            length: 60
            fixed: true
            nullable: false
        alternativeSpellings:
            type: string
            length: 128
            fixed: true
            nullable: true
            column: alternative_spellings
        relevancy:
            type: decimal
            nullable: true
    lifecycleCallbacks: {  }
