Users:
    type: entity
    table: users
    fields:
        autoId:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: auto_id
            generator:
                strategy: IDENTITY
        username:
            type: string
            length: 32
            fixed: true
            nullable: false
        password:
            type: string
            length: 64
            fixed: true
            nullable: false
        email:
            type: string
            length: 64
            fixed: true
            nullable: false
        type:
            type: string
            length: 10
            fixed: true
            nullable: false
        avatar:
            type: integer
            unsigned: true
            nullable: false
        modified:
            type: datetime
            nullable: false
        date:
            type: datetime
            nullable: false
        validatedDate:
            type: datetime
            nullable: true
            column: validated_date
        ip:
            type: string
            length: 32
            fixed: true
            nullable: true
        name:
            type: string
            length: 60
            fixed: true
            nullable: false
        lastName:
            type: string
            length: 60
            fixed: true
            nullable: false
            column: last_name
        languageId:
            type: boolean
            nullable: false
            column: language_id
        url:
            type: string
            length: 128
            fixed: true
            nullable: true
        sex:
            type: string
            length: 1
            fixed: true
            nullable: false
        country:
            type: string
            length: 50
            fixed: true
            nullable: true
        birthday:
            type: date
            nullable: false
        usernameRegister:
            type: string
            length: 32
            fixed: true
            nullable: true
            column: username_register
        emailRegister:
            type: string
            length: 64
            fixed: true
            nullable: true
            column: email_register
        googleId:
            type: string
            length: 32
            fixed: true
            nullable: true
            column: google_id
    lifecycleCallbacks: {  }
